version: "3.7"
services:
  consul:
    image: consul:latest
    command:
      - 'consul'
      - 'agent' 
      - '-data-dir=/consul/data'
      - '-config-dir=/consul/config'
      - '-server'
      - '-ui'
      - '-node=consul'
      - '-bootstrap-expect=1'
      - '-client=0.0.0.0'
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    volumes:
      - consul:/consul/data
    networks:
      - cluster

  postgres-1:
    image: pg-gis:12.9-2.5-bullseye
    command: '/var/lib/postgresql/.local/bin/patroni /etc/patroni/patroni.yml'
    volumes:
      - /tmp/cluster/postgres-1/data:/var/lib/postgresql/data
      - ./patroni/patroni-12-1.yml:/etc/patroni/patroni.yml:ro
      - ./sql:/var/lib/postgresql/sql:ro
    networks:
      - cluster

  postgres-2:
    image: pg-gis:12.9-2.5-bullseye
    command: '/var/lib/postgresql/.local/bin/patroni /etc/patroni/patroni.yml'
    volumes:
      - /tmp/cluster/postgres-2/data:/var/lib/postgresql/data
      - ./patroni/patroni-12-2.yml:/etc/patroni/patroni.yml:ro
      - ./sql:/var/lib/postgresql/sql:ro
    networks:
      - cluster
volumes:
    consul:
      driver: local

networks:
  cluster:
    external: true
